version: 2

models:
  - name: gld_customer_metrics
    description: Customer-level aggregated metrics and KPIs
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
      - name: total_revenue
        description: Total revenue from customer
        tests:
          - positive_values
      - name: total_orders
        description: Total number of orders placed
        tests:
          - positive_values
      - name: net_revenue
        description: Net revenue after discount
        tests:
          - positive_values
      - name: last_order_date
        description: Most recent order date
        tests:
          - no_future_dates

  - name: gld_product_performance
    description: Product-level sales performance and profitability metrics
    columns:
      - name: product_id
        description: Unique product identifier
        tests:
          - unique
          - not_null
      - name: total_revenue
        description: Total revenue generated by product
        tests:
          - positive_values
      - name: profit_margin_pct
        description: Profit margin percentage

  - name: gld_sales_summary
    description: Daily sales summary with key business metrics
    columns:
      - name: order_date
        description: Date of orders
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue for the day
        tests:
          - positive_values
      - name: unique_customers
        description: Number of unique customers who ordered
      - name: net_revenue
        description: Net revenue after discount
        tests:
          - positive_values
      - name: territory_group
        description: Territory grouping
      - name: category_id
        description: Product category id
      - name: subcategory_id
        description: Product subcategory id
