version: 2

models:
  - name: brnz_customers
    description: "Bronze layer customer data from AdventureWorks"
    columns:
      - name: CustomerID
        description: "Primary key for customer"
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int

      - name: FirstName
        description: "Customer first name (NULL for store customers)"

      - name: LastName
        description: "Customer last name (NULL for store customers)"

      - name: EmailPromotion
        description: "Email promotion preference"
        tests:
          - accepted_values:
              values: [0, 1, 2]

      - name: StoreID
        description: "Store identifier"

      - name: TerritoryID
        description: "Sales territory"

      - name: last_modified_date
        description: "Last modified timestamp"
        tests:
          - not_null

  - name: brnz_products
    description: "Bronze layer product data from AdventureWorks"
    columns:
      - name: ProductID
        description: "Primary key for product"
        tests:
          - unique
          - not_null
      - name: ProductName
        description: "Product name"
      - name: ProductNumber
        description: "Product number/SKU"
      - name: StandardCost
        description: "Standard cost"
        tests:
          - positive_values
      - name: ListPrice
        description: "List price"
        tests:
          - positive_values
      - name: ProductSubcategoryID
        description: "Subcategory id"
      - name: ProductCategoryID
        description: "Category id"
      - name: last_modified_date
        description: "Last modified timestamp"
        tests:
          - not_null

  - name: brnz_sales_orders
    description: "Bronze layer sales order data"
    columns:
      - name: sales_order_id
        description: "Primary key"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: int

      - name: order_date
        description: "Order date"
        tests:
          - not_null
          - no_future_dates

      - name: due_date
        description: "Due date"

      - name: ship_date
        description: "Ship date"

      - name: status
        description: "Order status"
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6]

      - name: online_order_flag
        description: "Online order flag"
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [0, 1]

      - name: sales_order_number
        description: "Sales order number"
        tests:
          - not_null

      - name: purchase_order_number
        description: "Purchase order number"

      - name: customer_id
        description: "Foreign key to customer"
        tests:
          - not_null
          - relationships:
              to: ref('brnz_customers')
              field: CustomerID

      - name: sales_person_id
        description: "Sales person ID"

      - name: territory_id
        description: "Territory ID"

      - name: tax_amount
        description: "Tax amount"
        tests:
          - positive_values

      - name: freight_amount
        description: "Freight amount"
        tests:
          - positive_values

      - name: subtotal_amount
        description: "Order subtotal"
        tests:
          - positive_values

      - name: total_due_amount
        description: "Total due"
        tests:
          - positive_values

      - name: last_modified_date
        description: "Last modified timestamp"
        tests:
          - not_null

      - name: order_detail_id
        description: "Order detail ID"
        tests:
          - not_null

      - name: product_id
        description: "Product ID"
        tests:
          - not_null

      - name: order_qty
        description: "Order quantity"
        tests:
          - positive_values

      - name: unit_price
        description: "Unit price"
        tests:
          - positive_values

      - name: unit_price_discount
        description: "Unit price discount"

      - name: line_total
        description: "Line total"
        tests:
          - positive_values

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - sales_order_id
            - order_detail_id

  - name: brnz_territory
    description: "Bronze layer sales territory data"
    columns:
      - name: territory_id
        description: "Territory id"
        tests:
          - unique
          - not_null
      - name: territory_name
        description: "Territory name"
      - name: territory_group
        description: "Territory grouping"
      - name: country_region_code
        description: "Country/region code"
      - name: sales_ytd
        description: "Year-to-date sales"
        tests:
          - positive_values
      - name: sales_last_year
        description: "Sales last year"
        tests:
          - positive_values
      - name: cost_ytd
        description: "Year-to-date cost"
        tests:
          - positive_values
      - name: cost_last_year
        description: "Cost last year"
        tests:
          - positive_values
      - name: last_modified_date
        description: "Last modified timestamp"
        tests:
          - not_null
